## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: python
os:
  - linux
addons:
    apt:
        packages:
            - gfortran
python:
  - 3.6
branches:
    only:
notifications:
  email: false
git:
  depth: 99999999
env:
  global:
    - DEVITO_ARCH="gcc"
    - DEVITO_OMP="0"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y gfortran
  - pip install --upgrade pip
  - pip install git+https://github.com/opesci/devito.git
  - pip install -r docker/devito_requirements.txt
  - CURL_USER_AGENT="Travis-CI $(curl --version | head -n 1)"
  - mkdir -p ~/julia
  - curl -A "$CURL_USER_AGENT" -s -L --retry 7 'https://julialang-s3.julialang.org/bin/linux/x64/1.1/julia-1.1.1-linux-x86_64.tar.gz' | tar -C ~/julia -x -z --strip-components=1 -f -
  - export PATH="${PATH}:${HOME}/julia/bin"
  - julia -e 'using Pkg; Pkg.clone("https://github.com/slimgroup/SeisIO.jl")'
  - julia -e 'using Pkg; Pkg.clone("https://github.com/slimgroup/JOLI.jl.git")'
  - julia -e 'using Pkg; Pkg.add("PyCall")'
install:
  - export PYTHON=$(which python)
  - julia -e 'using Pkg; Pkg.clone("https://github.com/slimgroup/JUDI.jl.git")'
script:
  - julia --check-bounds=yes --color=yes -e 'using Pkg; using Test; Pkg.test("JUDI", coverage=true)'
after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("JUDI")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())' 
